name: dienstleisto
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.0
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.0
  intl: ^0.19.0
  flutter_animation_progress_bar: ^2.3.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.7
  location: ^5.0.3
  im_stepper: ^1.0.1+1
  multi_select_flutter: ^4.1.3
  google_nav_bar: ^5.0.6
  file_picker: ^6.2.0
  dotted_border: ^2.1.0
  timeline_tile: ^2.0.0
  flutter_xlider: ^3.5.0
  geolocator: ^11.0.0
  rating_summary: ^1.0.2+1
  flutter_launcher_icons: ^0.13.1
  intl_phone_number_input: ^0.7.4
  cloud_firestore: ^4.15.9
  http: ^1.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/animations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
