// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCguX2Qf3swytQFmLFrcu9m75GFVTuLOpg',
    appId: '1:727644051148:web:d5350e972b15dbf061d469',
    messagingSenderId: '727644051148',
    projectId: 'werktion',
    authDomain: 'werktion.firebaseapp.com',
    storageBucket: 'werktion.appspot.com',
    measurementId: 'G-7FEKN0M1TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdw1zrOKKbdNjpFIyTm48ndXdL--zIQ2o',
    appId: '1:727644051148:android:2a3d245ce8364d7061d469',
    messagingSenderId: '727644051148',
    projectId: 'werktion',
    storageBucket: 'werktion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbOcFVRUd-4eZxkfDaUu-KqZ3nca2mJX0',
    appId: '1:727644051148:ios:17ba4a92c2bfc01561d469',
    messagingSenderId: '727644051148',
    projectId: 'werktion',
    storageBucket: 'werktion.appspot.com',
    iosBundleId: 'com.example.dienstleisto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbOcFVRUd-4eZxkfDaUu-KqZ3nca2mJX0',
    appId: '1:727644051148:ios:6e9fee272a5d32bf61d469',
    messagingSenderId: '727644051148',
    projectId: 'werktion',
    storageBucket: 'werktion.appspot.com',
    iosBundleId: 'com.example.dienstleisto.RunnerTests',
  );
}
